<footer>
  <p>
    Website content copyright &copy; 2014 Bangalore Astronomical Society.
  </p>
  <p>
    This website was designed using Twitter Bootstrap. Bootstrap is Copyright &copy; 2014 Twitter, and is released under the MIT License.
  </p>
</footer>

<!-- Bootstrap core JavaScript
     ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="bootstrap/js/bootstrap.min.js"></script>
